// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Blog {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  excerpt?: string;
  content?: PortableTextBlock[];
  category?: string;
  published_date?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Course {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  description?: PortableTextBlock[];
  short_description?: string;
  duration?: string;
  level?: string;
  fees?: string;
  features?: PortableTextBlock[];
  curriculum?: PortableTextBlock[];
  thumbnail?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  banner?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  seo_title?: string;
  seo_description?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Faq {
  id: string;
  slug: string | null;
  status: string;
  question: string;
  answer: string;
  category?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Menu {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  items?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  hero_eyebrow?: string;
  hero_heading?: string;
  hero_subtext?: string;
  hero_cta_primary?: string;
  hero_cta_primary_url?: string;
  hero_cta_secondary?: string;
  hero_cta_secondary_url?: string;
  content?: PortableTextBlock[];
  seo_title?: string;
  seo_description?: string;
  canonical_url?: string;
  og_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  alumni_text?: string;
  students_feedback_title?: string;
  students_feedback_desc?: string;
  courses_title?: string;
  course_1_title?: string;
  course_1_desc?: string;
  course_1_btn_primary?: string;
  course_1_btn_secondary?: string;
  course_2_title?: string;
  course_2_desc?: string;
  course_2_btn_primary?: string;
  course_2_btn_secondary?: string;
  steps_title?: string;
  step_1_num?: string;
  step_1_label?: string;
  step_2_num?: string;
  step_2_label?: string;
  step_3_num?: string;
  step_3_label?: string;
  steps_cta_text?: string;
  testimonials_eyebrow?: string;
  testimonials_title?: string;
  testimonials_desc?: string;
  testimonials_btn_text?: string;
  testimonial_1_badge?: string;
  testimonial_1_quote?: string;
  testimonial_1_name?: string;
  testimonial_1_role?: string;
  testimonial_2_badge?: string;
  testimonial_2_quote?: string;
  testimonial_2_name?: string;
  testimonial_2_role?: string;
  audience_1_overlay?: string;
  audience_1_title?: string;
  audience_1_desc?: string;
  audience_1_btn_text?: string;
  audience_2_overlay?: string;
  audience_2_title?: string;
  audience_2_desc?: string;
  audience_2_btn_text?: string;
  promo_title?: string;
  promo_btn_text?: string;
  feedback_1_name?: string;
  feedback_1_role?: string;
  feedback_2_name?: string;
  feedback_2_role?: string;
  feedback_3_name?: string;
  feedback_3_role?: string;
  feedback_4_name?: string;
  feedback_4_role?: string;
  feedback_5_name?: string;
  feedback_5_role?: string;
  feedback_6_name?: string;
  feedback_6_role?: string;
  think_banner_title?: string;
  think_1_quote?: string;
  think_1_name?: string;
  think_1_company?: string;
  think_2_quote?: string;
  think_2_name?: string;
  think_2_company?: string;
  think_3_quote?: string;
  think_3_name?: string;
  think_3_company?: string;
  achievements_title?: string;
  achievements_subtitle?: string;
  achievements_1_num?: string;
  achievements_1_label?: string;
  achievements_2_num?: string;
  achievements_2_label?: string;
  career_title?: string;
  partner_1_name?: string;
  partner_1_desc?: string;
  partner_2_name?: string;
  partner_2_desc?: string;
  partner_3_name?: string;
  partner_3_desc?: string;
  partner_4_name?: string;
  partner_4_desc?: string;
  life_title?: string;
  life_1_title?: string;
  life_1_desc?: string;
  life_2_title?: string;
  life_2_desc?: string;
  life_3_title?: string;
  life_3_desc?: string;
  life_4_title?: string;
  life_4_desc?: string;
  featured_title?: string;
  featured_subtitle?: string;
  hero_person_img?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  course_1_img?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  course_2_img?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  testimonial_1_avatar?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  testimonial_2_avatar?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  audience_1_img?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  audience_2_img?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  career_person_img?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  life_1_img?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  life_2_img?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  life_3_img?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  life_4_img?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Setting {
  id: string;
  slug: string | null;
  status: string;
  site_name?: string;
  contact_phone?: string;
  contact_email?: string;
  contact_address?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Testimonial {
  id: string;
  slug: string | null;
  status: string;
  student_name: string;
  course_name?: string;
  review?: string;
  rating?: number;
  photo?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Trainer {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  position?: string;
  bio?: PortableTextBlock[];
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  linkedin_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    blog: Blog;
    courses: Course;
    faq: Faq;
    menus: Menu;
    pages: Page;
    settings: Setting;
    testimonials: Testimonial;
    trainers: Trainer;
  }
}