// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Blog {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  excerpt?: string;
  content?: PortableTextBlock[];
  category?: string;
  published_date?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Course {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  description?: PortableTextBlock[];
  short_description?: string;
  duration?: string;
  level?: string;
  fees?: string;
  features?: PortableTextBlock[];
  curriculum?: PortableTextBlock[];
  thumbnail?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  banner?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  seo_title?: string;
  seo_description?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Faq {
  id: string;
  slug: string | null;
  status: string;
  question: string;
  answer: string;
  category?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Menu {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  items?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  hero_eyebrow?: string;
  hero_heading?: string;
  hero_subtext?: string;
  hero_cta_primary?: string;
  hero_cta_primary_url?: string;
  hero_cta_secondary?: string;
  hero_cta_secondary_url?: string;
  content?: PortableTextBlock[];
  seo_title?: string;
  seo_description?: string;
  canonical_url?: string;
  og_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Setting {
  id: string;
  slug: string | null;
  status: string;
  site_name?: string;
  contact_phone?: string;
  contact_email?: string;
  contact_address?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Testimonial {
  id: string;
  slug: string | null;
  status: string;
  student_name: string;
  course_name?: string;
  review?: string;
  rating?: number;
  photo?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Trainer {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  position?: string;
  bio?: PortableTextBlock[];
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  linkedin_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    blog: Blog;
    courses: Course;
    faq: Faq;
    menus: Menu;
    pages: Page;
    settings: Setting;
    testimonials: Testimonial;
    trainers: Trainer;
  }
}